name: "Unlock git-crypt secrets in specific folder"
description: "Unlock git-crypt files with a simple alpine based Docker image"
author: "Marcelo"
branding:
  icon: "unlock"
  color: "green"
runs:
  using: "docker"
  image: "Dockerfile"
